apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: werewolves-fyi-cert
spec:
  secretName: werewolves-fyi-tls
  renewBefore: 240h
  duration: 2160h
  commonName: werewolves.fyi
  dnsNames:
  - werewolves.fyi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
