apiVersion: apps/v1
kind: Deployment
metadata:
  name: werewolves-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: werewolves-fyi
  template:
    metadata:
      labels:
        app: werewolves-fyi
    spec:
      containers:
      - name: werewolves-fyi
        image: registry.werewolves.fyi/werewolves.fyi:v0.0.11
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
      - name: werewolves-registry-creds
