---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-docker-registry-pvc
  namespace: docker-registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
  namespace: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: lv-storage
          mountPath: /var/lib/registry
          subPath: registry
        - name: auth
          mountPath: /auth
          readOnly: true
        - name: certs
          mountPath: /certs
          readOnly: true
        env:
        - name: REGISTRY_HTTP_SECRET
          valueFrom:
            secretKeyRef:
              name: registry-http-secret
              key: http.secret
        - name: REGISTRY_HTTP_ADDR
          value: "0.0.0.0:5000"
        - name: REGISTRY_HTTP_HEADERS
          value: '{"X-Forwarded-Proto": ["https"]}'
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: longhorn-docker-registry-pvc
        - name: certs
          secret:
            secretName: docker-registry-tls-secret
        - name: auth
          secret:
            secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: docker-registry
spec:
  selector:
    app: registry
  type: LoadBalancer
  loadBalancerIP: 192.168.86.201
  ports:
    - name: docker-port
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-cert
  namespace: docker-registry
spec:
  secretName: docker-registry-tls-secret
  duration: 2160h
  renewBefore: 360h
  dnsNames:
  - registry.werewolves.fyi
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: docker-registry
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  rules:
  - host: registry.werewolves.fyi
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: registry-service
              port:
                number: 5000
  tls:
  - hosts:
    - registry.werewolves.fyi
    secretName: docker-registry-tls-secret
