apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-rwx-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: arr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:5.26.2
        imagePullPolicy: Always
        ports:
        - containerPort: 7878
        env:
        - name: PUID
          value: "1002"
        - name: PGID
          value: "1002"
        - name: TZ
          value: "America/New_York"
        volumeMounts:
        - name: downloads
          mountPath: /downloads
        - name: config
          mountPath: /config
      volumes:
      - name: downloads
        persistentVolumeClaim:
          claimName: porygon-pvc
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config-rwx-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: arr
spec:
  selector:
    app: radarr
  ports:
  - name: http
    port: 80
    targetPort: 7878

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: arr
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
      - radarr.pokedex.lan
    secretName: radarr-tls
  rules:
  - host: radarr.pokedex.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80

