apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-werewolves-cluster
spec:
  instances: 3
  storage:
    storageClass: longhorn-1r
    size: 15Gi
  walStorage:
    storageClass: longhorn-1r
    size: 1Gi
  postgresql:
    parameters:
      random_page_cost: "1.1"
      log_statement: "ddl"
      log_checkpoints: "on"
  managed:
    roles:
    - name: manager
      ensure: present
      comment: Cluster manager
      login: true
      superuser: false
      createdb: true
      createrole: true
      passwordSecret:
        name: werewolves-manager
