apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: test-werewolves-cluster
  name: test-werewolves-cluster-lb
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - nodePort: 30519
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: test-werewolves-cluster
    cnpg.io/instanceRole: primary
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.86.203
      ipMode: VIP
