apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: werewolves-data-cluster
  name: werewolves-data-cluster-lb
spec:
  allocateLoadBalancerNodePorts: true
  ports:
  - nodePort: 30519
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: werewolves-data-cluster
    cnpg.io/instanceRole: primary
  type: LoadBalancer
  loadBalancerIP: 192.168.86.203
