---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: golinks-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golinks-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: golinks
  template:
    metadata:
      labels:
        app: golinks
    spec:
      initContainers:
      - name: init-links-file
        image: alpine:3.18
        command: ['sh', '-c', 'touch /etc/golinks/links']
        volumeMounts:
        - name: golinks-pvc
          mountPath: /etc/golinks
      containers:
      - name: golinks
        image: registry.werewolves.fyi/golinks:v1.0.4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: golinks-pvc
          mountPath: /etc/golinks
      imagePullSecrets:
      - name: werewolves-registry-creds
      volumes:
      - name: golinks-pvc
        persistentVolumeClaim:
          claimName: golinks-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: golinks-service
spec:
  selector:
    app: golinks
  type: LoadBalancer
  loadBalancerIP: 192.168.86.204
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
